language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t webapp-production -f Dockerfile.dev .

script:
  - docker run -e CI=true webapp-production npm run test

after_success:
  - docker build -t webapp-production .
  - echo "sh@yan123698741" | docker login -u "mrsimti" --password-stdin
  - docker push webapp-production
